# numpy

In [1]:
# create 1D array
import numpy as np
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

#### 2D array

In [2]:
arr = np.array([[1,2], [3,4]])
arr



array([[1, 2],
       [3, 4]])

### arange(start, stop)
used to create an array, it is similar to range() function 


In [4]:
arr = np.arange(2, 10)
print(arr)
print(type(arr))

[2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


### array of zeros
    -numpy.zeros(shape)
    -shape means (n_rows, n_cols)

In [7]:
arr = np.zeros((2,3))
print(arr)
print(arr.dtype)  # gives type of values


[[0. 0. 0.]
 [0. 0. 0.]]
float64


### Linearly spaced array
- numpy.linspace(start, stop, no_of_values)
- linearly spaced means, common difference is same

In [8]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [10]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

### creating an array(Method 2)
- numpy.asarray(seq, dtype=None)
- used for converting Python sequence into ndarrays

In [14]:
a = [1, 2, 3]
arr = np.asarray(a)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


### reshaping
- numpy.reshape(new_shape)
- changing the dimensions

In [24]:
arr = np.zeros(8) # 1D array
print(arr)
print(arr.ndim)  # ndim attr returns number of dimensions of an array
arr3d = arr.reshape((2,2,2))
print(arr3d)
print("2D array")
arr2d = arr.reshape((4,2))
print(arr2d)

[0. 0. 0. 0. 0. 0. 0. 0.]
1
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
2D array
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # 1D array
arr3d = arr.reshape((2,2,2))
print(arr3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flatten the array
- convert multidimenstional array to 1D array
- array.ravel()


In [26]:
import numpy as np
arr_1d = np.zeros(8)
arr3d = arr_1d.reshape((2,2,2))
arr = arr3d.ravel()
print(arr)


[0. 0. 0. 0. 0. 0. 0. 0.]


# Indexing
- indexing concept is same as list

In [30]:
import numpy as np
arr = np.arange(2, 30)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29]


In [31]:
# access element using index
arr[0]  # first value

2

In [32]:
arr[-1]  # last value

29

In [33]:
arr[1]  # second value

3

# slicing

In [39]:
import numpy as np
arr = np.arange(2, 20)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [40]:
# slicing array is similar to list
arr[1:5]

array([3, 4, 5, 6])

In [42]:
arr[1:15:3] #  start:stop:step  same as list

array([ 3,  6,  9, 12, 15])

In [45]:
arr[2:]  # stop index is missing: returns value till the end

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
arr[:5]  # start index is missing : returns value from the beginning

array([2, 3, 4, 5, 6])

### arrays give you more options in slicing in comprison to list


In [44]:
arr_slice = slice(1, 10, 3)  # (start, stop, step)
arr[arr_slice]

array([3, 6, 9])

### Slicing 2D array

In [53]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
# slicing it syntax :myarray[row_slice, column_slice]
arr_2d[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [55]:
arr_2d[0:2,0:1]

array([[1],
       [4]])

In [57]:
arr = np.array([[1, 2, 3, 100, 200],
                [4, 5, 6, 300, 400],
                [7, 8, 9, 500, 600],
               [11, 12, 13, 14, 15]])
print(arr)

[[  1   2   3 100 200]
 [  4   5   6 300 400]
 [  7   8   9 500 600]
 [ 11  12  13  14  15]]


In [58]:
# to slice 2D array, you can provide separte slices for rows and columns
arr[0:2,0:3]

array([[1, 2, 3],
       [4, 5, 6]])

### Array attributes

In [62]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [65]:
# shape : (rows, cols)
arr.shape

(4, 5)

In [66]:
# number of dimensions
# ndim
arr.ndim

2

In [67]:
# itemsize of one element of an array
arr.itemsize

8

### uninitialized array
array of some random values

In [69]:
np.empty((3,4), dtype=int)

array([[-1152921504606846976, -1152921504606846976,                   19,
                           0],
       [                   0,  8028074745930326651,  2464364226844172910,
         4189022153932546604],
       [ 4048785784372736546,  3619264836039684397,  3978987643847522868,
         8296241989623691570]])

## Loading an array from a file

In [72]:
import numpy as np
input_path = r'/Users/gyanendra/Desktop/PyDataScience_venv/Module4/numpy_examples/filex.txt'
arr = np.loadtxt(input_path, dtype=int)
print(arr)

[[1 2 3 4 5 6 7]
 [2 3 4 5 5 1 8]]


### transfer array to a file

In [76]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt('output_array.txt', arr, fmt="%1.1e")

In [78]:
# changing the separator from space to $
np.savetxt('output_array.txt', arr, fmt="%1.2e", delimiter='$')
print(np.savetxt.__doc__) # to see documentation


    Save an array to a text file.

    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
            a) a single specifier, `fmt='%.4e'`, resulting in numbers formatted
               like `' (%s+%sj)' % (fmt, fmt)`
            b) a full string specifying every real and imaginary part, e.g.
               `' %.4e %+.4ej %.4e %+.4ej %.4e %+.4ej'` for 3 columns
            c) a list of specifiers, one per column - in this case, the real
               and imaginary part must ha