# Module 4

## numpy

In [100]:
# creating an array
import numpy as np


In [101]:
# 1D array
arr = np.array([11, 22, 33, 44])
arr

array([11, 22, 33, 44])

In [102]:
type(arr)


numpy.ndarray

In [103]:
arr.ndim  # dimension of an array

1

In [104]:
# 2D array
arr = np.array([[11, 22, 10], [33, 44, 30]])
arr

array([[11, 22, 10],
       [33, 44, 30]])

In [105]:
arr.shape

(2, 3)

In [106]:
arr.ndim  # dimension of an array

2

In [107]:
# arange(start, stop, step)
np.arange(2, 30, 3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [108]:
# array of zeros: np.zeros(shape)
arr = np.zeros((2, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
# check data type of an array elements
arr.dtype

dtype('float64')

In [110]:
# itemsize in bytes
arr.itemsize

8

In [111]:
# choose the datatype of elements in an array using dtype=

arr = np.zeros((2, 4), dtype=int)
arr


array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [112]:
arr.dtype

dtype('int64')

In [113]:
# # choose the datatype of elements
arr =  np.array([1,2,3], dtype=np.int8)
arr

array([1, 2, 3], dtype=int8)

In [114]:
arr.dtype

dtype('int8')

In [115]:
arr.itemsize

1

In [116]:
# # choose the datatype of elements
arr =  np.array([1,2,3], dtype=np.float16)
arr

array([1., 2., 3.], dtype=float16)

In [117]:
arr.dtype

dtype('float16')

In [118]:
# linspace()
np.linspace(2, 10, 3)

array([ 2.,  6., 10.])

In [119]:
np.linspace(2, 10, 4)

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [120]:
# reshaping of an array
# NOTE: number of elements must remain same after reshaping
arr1 = np.array([11, 22, 33, 44, 55, 66, 77, 88])
arr1

array([11, 22, 33, 44, 55, 66, 77, 88])

In [121]:
# convert it to 2D array
arr1.reshape((2, 4))

array([[11, 22, 33, 44],
       [55, 66, 77, 88]])

In [122]:
arr_3d = arr1.reshape((2, 2, 2))
arr_3d

array([[[11, 22],
        [33, 44]],

       [[55, 66],
        [77, 88]]])

In [123]:
# flatten an array arr.ravel()
arr_3d

array([[[11, 22],
        [33, 44]],

       [[55, 66],
        [77, 88]]])

In [124]:
arr_1d = arr_3d.ravel()
arr_1d

array([11, 22, 33, 44, 55, 66, 77, 88])

## Indexing

In [125]:
## 1D array

In [126]:
arr = np.array([11, 22, 33, 44, 55, 66, 77])
arr

array([11, 22, 33, 44, 55, 66, 77])

In [127]:
arr[0]

11

In [128]:
arr[-1]

77

In [129]:
arr[2]

33

In [130]:
# slicing 1D array
arr[1:5]   # index 1, 2, 3, 4

array([22, 33, 44, 55])

In [131]:
# 2D array indexing
arr = np.array([[11, 22, 10, 20], [33, 44, 30, 40], [55, 66, 77, 50],
               [99, 88, 77, 66]])
arr


array([[11, 22, 10, 20],
       [33, 44, 30, 40],
       [55, 66, 77, 50],
       [99, 88, 77, 66]])

In [132]:
#arr[row_index, column_index]
arr[1,1]

44

In [133]:
arr[1][1]

44

In [134]:
# slicing arr[row_slice, column_slice]
arr

array([[11, 22, 10, 20],
       [33, 44, 30, 40],
       [55, 66, 77, 50],
       [99, 88, 77, 66]])

In [135]:
arr[1:3,1:3]

array([[44, 30],
       [66, 77]])

In [136]:
## accessing rows
arr[1:3]

array([[33, 44, 30, 40],
       [55, 66, 77, 50]])

In [137]:
arr[1:3,]

array([[33, 44, 30, 40],
       [55, 66, 77, 50]])

In [138]:
# arr[start:Stop:step, start:stop:step]
myslice = arr[1:100:2,1:100:2]
myslice

array([[44, 40],
       [88, 66]])

In [139]:
myslice.ravel()

array([44, 40, 88, 66])

In [140]:
a = [11, 22, 33, 44, 55]
a[1:10:3]  # a[1], a[4], a[7], 

[22, 55]

In [141]:
# an array with some random values
np.empty((2,3))

array([[5.45352918e-312, 1.26480805e-321, 0.00000000e+000],
       [0.00000000e+000, 1.75871011e-310, 3.50977866e+064]])

## Reding and writing from text files

In [149]:
arr = np.loadtxt('filex.txt')
arr

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [45.,  3.,  4.,  5.,  5.,  1.,  8.],
       [56.,  3.,  4.,  5.,  5.,  1.,  8.],
       [89.,  3.,  4.,  5.,  5.,  1.,  8.],
       [44.,  3.,  4.,  5.,  5.,  1.,  8.],
       [44.,  3.,  4.,  5.,  5., 33.,  8.]])

In [143]:
arr.shape

(6, 7)

In [144]:
arr.dtype

dtype('float64')

In [150]:
arr.itemsize

8

In [145]:
arr = np.loadtxt('filex.txt', dtype=np.int8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [45,  3,  4,  5,  5,  1,  8],
       [56,  3,  4,  5,  5,  1,  8],
       [89,  3,  4,  5,  5,  1,  8],
       [44,  3,  4,  5,  5,  1,  8],
       [44,  3,  4,  5,  5, 33,  8]], dtype=int8)

In [146]:
arr.dtype

dtype('int8')

In [147]:
arr.itemsize

1

In [153]:
arr = np.loadtxt(r'/Users/gyanendrakumar/PycharmProjects/Edureka_DS/Module_4/filex.txt', dtype=np.int8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [45,  3,  4,  5,  5,  1,  8],
       [56,  3,  4,  5,  5,  1,  8],
       [89,  3,  4,  5,  5,  1,  8],
       [44,  3,  4,  5,  5,  1,  8],
       [44,  3,  4,  5,  5, 33,  8]], dtype=int8)

In [157]:
help(np.loadtxt)

Help on function loadtxt in module numpy:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None)
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
  

In [155]:
np.loadtxt('filex.txt', skiprows=3)

array([[89.,  3.,  4.,  5.,  5.,  1.,  8.],
       [44.,  3.,  4.,  5.,  5.,  1.,  8.],
       [44.,  3.,  4.,  5.,  5., 33.,  8.]])

In [159]:
np.loadtxt('filex.txt', skiprows=3,usecols = (1,4,5))

array([[ 3.,  5.,  1.],
       [ 3.,  5.,  1.],
       [ 3.,  5., 33.]])

In [161]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [45,  3,  4,  5,  5,  1,  8],
       [56,  3,  4,  5,  5,  1,  8],
       [89,  3,  4,  5,  5,  1,  8],
       [44,  3,  4,  5,  5,  1,  8],
       [44,  3,  4,  5,  5, 33,  8]], dtype=int8)

In [168]:
# export this array into a file
np.savetxt('batch3rdAug_array.txt',
           arr,
          fmt='%d',
          delimiter='$')


In [165]:
help(np.savetxt)

Help on function savetxt in module numpy:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4

# Pandas

## Series

In [170]:
import pandas as pd

In [171]:
ser = pd.Series([11, 22, 33, 44])
ser

0    11
1    22
2    33
3    44
dtype: int64

In [172]:
arr = np.array([10, 20, 30])
ser = pd.Series(arr)
ser

0    10
1    20
2    30
dtype: int64

In [173]:
# dict keys would become series 'indexes'
d = {'a':10, 'b':20, 'c':30}
ser = pd.Series(d)
ser

a    10
b    20
c    30
dtype: int64

In [174]:
ser['a']

10

In [175]:
ser['b']

20

## DataFrames

In [176]:
# creating
# list of dictionaries
d = [{'a':11, 'b':22, 'c':33}, {'a':1, 'b':2}]
df = pd.DataFrame(d)
df

a   b     c
0  11  22  33.0
1   1   2   NaN

In [ ]:
#NaN : not a number

In [177]:
# creating and user defined indexes
d = [{'a':11, 'b':22, 'c':33}, {'a':1, 'b':2}]
df = pd.DataFrame(d, index=['first','second'])
df

a   b     c
first   11  22  33.0
second   1   2   NaN

In [178]:
# Is NaN equal to null ?


False

In [179]:
df

a   b     c
first   11  22  33.0
second   1   2   NaN

In [180]:
# adding a new column
df['new_column'] = [100, 200]
df

a   b     c  new_column
first   11  22  33.0         100
second   1   2   NaN         200

In [181]:
del df['new_column']
df

a   b     c
first   11  22  33.0
second   1   2   NaN

In [182]:
df.pop('c')

first     33.0
second     NaN
Name: c, dtype: float64

### accessing rows in a dataframe
- loc and iloc

In [ ]:
# access row using the row lable
# syntax: df.loc['row_lable']
df.loc['b']

In [185]:
data = {'one':pd.Series([11,22,33],index=['a', 'b', 'c']),
     'two':pd.Series([1,2,3,4], index=['a', 'b','c','d'])}

df = pd.DataFrame(data)
df

one  two
a  11.0    1
b  22.0    2
c  33.0    3
d   NaN    4

In [187]:
df.loc['a']

one    11.0
two     1.0
Name: a, dtype: float64

In [188]:
# access a row using index posiiton
# Synatx: df.iloc[row_index_position]
df.iloc[0]

one    11.0
two     1.0
Name: a, dtype: float64

In [189]:
df.iloc[1]

one    22.0
two     2.0
Name: b, dtype: float64

In [192]:
# Dataframe- Row addition
# df.append()
data = {'one':pd.Series([11,22,33],index=['a', 'b', 'c']),
     'two':pd.Series([1,2,3,4], index=['a', 'b','c','d']),
       'three':pd.Series([100,20,300], index=['a', 'b','c'])}

df = pd.DataFrame(data)
df


one  two  three
a  11.0    1  100.0
b  22.0    2   20.0
c  33.0    3  300.0
d   NaN    4    NaN

In [193]:
row = pd.DataFrame([[11,12], [13, 14]], columns=['two', 'three'])
row

two  three
0   11     12
1   13     14

In [194]:
print("Appending the row into an existing DF")
df = df.append(row, sort=False)
df

Appending the row into an existing DF


one  two  three
a  11.0    1  100.0
b  22.0    2   20.0
c  33.0    3  300.0
d   NaN    4    NaN
0   NaN   11   12.0
1   NaN   13   14.0

In [195]:
# what if I want to use iloc here??
df.loc[0]

one       NaN
two      11.0
three    12.0
Name: 0, dtype: float64

In [196]:
df.iloc[0]

one       11.0
two        1.0
three    100.0
Name: a, dtype: float64